// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpoMatic3000.Infrastructure.Persistence;

#nullable disable

namespace OpoMatic3000.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OpoMatic3000DbContext))]
    [Migration("20260818163336_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OpoMatic3000.Domain.Attempts.TestAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("CorrectCount")
                        .HasColumnType("int");

                    b.Property<int>("IncorrectCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Score")
                        .HasPrecision(9, 6)
                        .HasColumnType("decimal(9,6)");

                    b.Property<short>("ScoringRuleVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int");

                    b.Property<int>("UnansweredCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAtUtc")
                        .IsDescending()
                        .HasDatabaseName("IX_TestAttempts_CompletedAtUtc_DESC");

                    b.HasIndex("SubmissionId")
                        .IsUnique()
                        .HasDatabaseName("UX_TestAttempts_SubmissionId");

                    b.ToTable("TestAttempts", null, t =>
                        {
                            t.HasCheckConstraint("CK_TestAttempts_Counts_NonNegative", "[CorrectCount] >= 0 AND [IncorrectCount] >= 0 AND [UnansweredCount] >= 0");

                            t.HasCheckConstraint("CK_TestAttempts_Counts_Total", "[CorrectCount] + [IncorrectCount] + [UnansweredCount] = [TotalQuestions]");

                            t.HasCheckConstraint("CK_TestAttempts_Score", "[Score] BETWEEN -2.5 AND 10");

                            t.HasCheckConstraint("CK_TestAttempts_ScoringRuleVersion", "[ScoringRuleVersion] > 0");

                            t.HasCheckConstraint("CK_TestAttempts_TotalQuestions", "[TotalQuestions] > 0");
                        });
                });

            modelBuilder.Entity("OpoMatic3000.Domain.Attempts.TestAttemptOption", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<byte>("DisplayOrder")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("bit");

                    b.Property<int>("OriginalOptionId")
                        .HasColumnType("int");

                    b.Property<long>("TestAttemptQuestionId")
                        .HasColumnType("bigint");

                    b.Property<string>("TextSnapshot")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("OriginalOptionId");

                    b.HasIndex("TestAttemptQuestionId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_TestAttemptOptions_Question_DisplayOrder");

                    b.HasIndex("TestAttemptQuestionId", "OriginalOptionId")
                        .IsUnique()
                        .HasDatabaseName("UX_TestAttemptOptions_Question_OriginalOption");

                    b.ToTable("TestAttemptOptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_TestAttemptOptions_DisplayOrder", "[DisplayOrder] BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("OpoMatic3000.Domain.Attempts.TestAttemptQuestion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("OriginalQuestionId")
                        .HasColumnType("int");

                    b.Property<int>("OriginalTopicId")
                        .HasColumnType("int");

                    b.Property<byte>("Result")
                        .HasColumnType("tinyint");

                    b.Property<string>("StatementSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("TestAttemptId")
                        .HasColumnType("bigint");

                    b.Property<string>("TopicNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("OriginalQuestionId");

                    b.HasIndex("OriginalTopicId")
                        .HasDatabaseName("IX_TestAttemptQuestions_OriginalTopicId");

                    b.HasIndex("TestAttemptId", "DisplayOrder")
                        .IsUnique()
                        .HasDatabaseName("UX_TestAttemptQuestions_Attempt_DisplayOrder");

                    b.HasIndex("TestAttemptId", "OriginalQuestionId")
                        .IsUnique()
                        .HasDatabaseName("UX_TestAttemptQuestions_Attempt_OriginalQuestion");

                    b.HasIndex("TestAttemptId", "OriginalTopicId");

                    b.ToTable("TestAttemptQuestions", null, t =>
                        {
                            t.HasCheckConstraint("CK_TestAttemptQuestions_DisplayOrder", "[DisplayOrder] > 0");

                            t.HasCheckConstraint("CK_TestAttemptQuestions_Result", "[Result] BETWEEN 0 AND 2");
                        });
                });

            modelBuilder.Entity("OpoMatic3000.Domain.Attempts.TestAttemptTopic", b =>
                {
                    b.Property<long>("TestAttemptId")
                        .HasColumnType("bigint");

                    b.Property<int>("OriginalTopicId")
                        .HasColumnType("int");

                    b.Property<string>("TopicNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("TestAttemptId", "OriginalTopicId");

                    b.HasIndex("OriginalTopicId");

                    b.ToTable("TestAttemptTopics", (string)null);
                });

            modelBuilder.Entity("OpoMatic3000.Domain.Questions.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Statement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("TopicId", "IsActive")
                        .HasDatabaseName("IX_Questions_TopicId_IsActive");

                    b.ToTable("Questions", (string)null);
                });

            modelBuilder.Entity("OpoMatic3000.Domain.Questions.QuestionOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("bit");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId", "Position")
                        .IsUnique()
                        .HasDatabaseName("UX_QuestionOptions_QuestionId_Position");

                    b.ToTable("QuestionOptions", null, t =>
                        {
                            t.HasCheckConstraint("CK_QuestionOptions_Position", "[Position] BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("OpoMatic3000.Domain.Questions.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .UseCollation("Latin1_General_100_CI_AS");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_Topics_IsActive");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Topics_Name");

                    b.ToTable("Topics", null, t =>
                        {
                            t.HasCheckConstraint("CK_Topics_Name_Trimmed", "[Name] = LTRIM(RTRIM([Name])) AND LEN([Name]) > 0");
                        });
                });

            modelBuilder.Entity("OpoMatic3000.Domain.Attempts.TestAttemptOption", b =>
                {
                    b.HasOne("OpoMatic3000.Domain.Questions.QuestionOption", "OriginalOption")
                        .WithMany()
                        .HasForeignKey("OriginalOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpoMatic3000.Domain.Attempts.TestAttemptQuestion", "TestAttemptQuestion")
                        .WithMany("Options")
                        .HasForeignKey("TestAttemptQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalOption");

                    b.Navigation("TestAttemptQuestion");
                });

            modelBuilder.Entity("OpoMatic3000.Domain.Attempts.TestAttemptQuestion", b =>
                {
                    b.HasOne("OpoMatic3000.Domain.Questions.Question", "OriginalQuestion")
                        .WithMany()
                        .HasForeignKey("OriginalQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpoMatic3000.Domain.Questions.Topic", "OriginalTopic")
                        .WithMany()
                        .HasForeignKey("OriginalTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpoMatic3000.Domain.Attempts.TestAttempt", "TestAttempt")
                        .WithMany("Questions")
                        .HasForeignKey("TestAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OpoMatic3000.Domain.Attempts.TestAttemptTopic", "AttemptTopic")
                        .WithMany()
                        .HasForeignKey("TestAttemptId", "OriginalTopicId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AttemptTopic");

                    b.Navigation("OriginalQuestion");

                    b.Navigation("OriginalTopic");

                    b.Navigation("TestAttempt");
                });

            modelBuilder.Entity("OpoMatic3000.Domain.Attempts.TestAttemptTopic", b =>
                {
                    b.HasOne("OpoMatic3000.Domain.Questions.Topic", "OriginalTopic")
                        .WithMany()
                        .HasForeignKey("OriginalTopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OpoMatic3000.Domain.Attempts.TestAttempt", "TestAttempt")
                        .WithMany("Topics")
                        .HasForeignKey("TestAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OriginalTopic");

                    b.Navigation("TestAttempt");
                });

            modelBuilder.Entity("OpoMatic3000.Domain.Questions.Question", b =>
                {
                    b.HasOne("OpoMatic3000.Domain.Questions.Topic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("OpoMatic3000.Domain.Questions.QuestionOption", b =>
                {
                    b.HasOne("OpoMatic3000.Domain.Questions.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("OpoMatic3000.Domain.Attempts.TestAttempt", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Topics");
                });

            modelBuilder.Entity("OpoMatic3000.Domain.Attempts.TestAttemptQuestion", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("OpoMatic3000.Domain.Questions.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("OpoMatic3000.Domain.Questions.Topic", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
